trigger:
  branches:
    include:
      - main
  tags:
    include:
      - "*"

pool:
  vmImage: "ubuntu-18.04"

variables:
  isTag: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/')]
  CI: 1

jobs:
  - job: Documentation
    steps:
      - task: UsePythonVersion@0
        displayName: 'Use Python 3.8'
        inputs:
          versionSpec: '3.8'
          addToPath: true

      - script: |
          python -m pip install flit
          flit install --symlink --extras=docs
        displayName: "Setup"
      - script: |
          cd docs
          make html
        displayName: "Build"