trigger:
  - main
  - tags

pool:
  vmImage: "ubuntu-18.04"

variables:
  isTag: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/')]
  CI: 1

jobs:
  - job: BuildAndTest
    steps:
      - task: UsePythonVersion@0
        displayName: 'Use Python 3.8'
        inputs:
          versionSpec: '3.8'
          addToPath: true

      - script: |
          python -m pip install .["test"]
        displayName: "Build"
      - script: |
          pytest
        displayName: "Test"
      - script: |
          python -m pip install pre-commit
          pre-commit run --all-files
        displayName: "Lint"

  - job: Documentation
    steps:
      - task: UsePythonVersion@0
        displayName: 'Use Python 3.8'
        inputs:
          versionSpec: '3.8'
          addToPath: true

      - script: |
          python -m pip install flit
          flit install --symlink --extras=docs
        displayName: "Setup"
      - script: |
          cd docs
          make html
        displayName: "Build"

  - job: Publish
    steps:
      - task: UsePythonVersion@0
        displayName: 'Use Python 3.8'
        inputs:
          versionSpec: '3.8'
          addToPath: true

      # Install python distributions like wheel, twine etc
      - script: |
          pip install wheel twine flit

      # Build the python distribution from source
      - script: |
          flit build

      - task: TwineAuthenticate@1
        displayName: 'Twine Authenticate'
        inputs:
          artifactFeed: Planetary Computer Components/pcpi

      # Use command line script to 'twine upload', use -r to pass the repository name and --config-file to pass the environment variable set by the authenticate task.
      - script: |
          python -m twine upload -r pcpi --config-file $(PYPIRC_PATH) dist/*.whl

    dependsOn: BuildAndTest
    condition: eq(variables.isTag, true)
